In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
##modelling 
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor 
from xgboost import XGBRegressor 
import warnings

In [2]:
%pip install catboost

Requirement already satisfied: catboost in c:\Users\Shronik\anaconda3\Lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (3.11.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (2.4.6)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (3.0.3)
Requirement already satisfied: scipy in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (1.18.0)
Requirement already satisfied: plotly in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in c:\Users\Shronik\anaconda3\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Shronik\anaconda3\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Shronik\anaconda3\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Shronik\anaconda3\Lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\Shronik\anaconda3\Lib\site-packages (from plotly->catboost) (2.23.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install xgboost

Requirement already satisfied: xgboost in c:\Users\Shronik\anaconda3\Lib\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\Users\Shronik\anaconda3\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in c:\Users\Shronik\anaconda3\Lib\site-packages (from xgboost) (1.18.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
df = pd.read_csv('stud.csv')

In [5]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [9]:
X = df.drop('math_score', axis=1)

In [15]:
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [16]:
Y=df['math_score']

In [17]:
Y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [20]:
num_features = X.select_dtypes(exclude="str").columns
cat_features = X.select_dtypes(include="str").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ( "standardscaler",numeric_transformer,num_features),
    ]
)

In [21]:
X = preprocessor.fit_transform(X)

In [22]:
X

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]], shape=(1000, 19))

In [23]:
X.shape

(1000, 19)

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((800, 19), (200, 19))